name: Build and Release

# Trigger the workflow whenever a new tag is pushed:
on:
  push:
    tags:
      - 'v*'  # Example: Tags starting with 'v' (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Use Ubuntu for Debian compatibility

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: sudo apt-get install libarchive-dev libfuse-dev

      # Build the project
      - name: Build
        run: make 
      # Create a release and attach the binary
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./out/fuse-archive
